"""表示する銘柄・指数の定義。ここを編集すればサイトの掲載内容が変わる。"""

GROUPS = [
    {
        "id": "indices",
        "name": "主要株価指数",
        "note": "世界の代表的な株価指数",
        "items": [
            ("^GSPC", "S&P 500", "米国"),
            ("^IXIC", "NASDAQ総合", "米国"),
            ("^DJI", "NYダウ", "米国"),
            ("^RUT", "ラッセル2000", "米国"),
            ("^N225", "日経平均株価", "日本"),
            ("TPY=F", "TOPIX先物", "日本"),
            ("^STOXX50E", "ユーロ・ストックス50", "欧州"),
            ("^GDAXI", "DAX", "ドイツ"),
            ("^FTSE", "FTSE 100", "英国"),
            ("^FCHI", "CAC 40", "フランス"),
            ("^HSI", "ハンセン指数", "香港"),
            ("000001.SS", "上海総合", "中国"),
            ("^KS11", "KOSPI", "韓国"),
            ("^TWII", "台湾加権", "台湾"),
            ("^BSESN", "SENSEX", "インド"),
            ("^AXJO", "S&P/ASX 200", "豪州"),
            ("^BVSP", "ボベスパ", "ブラジル"),
        ],
    },
    {
        "id": "risk",
        "name": "ボラティリティ・金利",
        "note": "市場の警戒感と金利水準",
        "items": [
            ("^VIX", "VIX指数", "米国株の恐怖指数"),
            ("^VIX3M", "VIX 3ヶ月", "3ヶ月先の変動率"),
            ("^VXN", "VXN指数", "NASDAQ100の変動率"),
            ("^MOVE", "MOVE指数", "米国債の変動率"),
            ("^TNX", "米10年債利回り", "%"),
            ("^TYX", "米30年債利回り", "%"),
            ("^FVX", "米5年債利回り", "%"),
        ],
    },
    {
        "id": "fx",
        "name": "為替・コモディティ",
        "note": "通貨と商品市況",
        "items": [
            ("USDJPY=X", "米ドル/円", "USD/JPY"),
            ("EURJPY=X", "ユーロ/円", "EUR/JPY"),
            ("GBPJPY=X", "英ポンド/円", "GBP/JPY"),
            ("EURUSD=X", "ユーロ/米ドル", "EUR/USD"),
            ("DX-Y.NYB", "ドル指数", "DXY"),
            ("GC=F", "金", "COMEX先物"),
            ("SI=F", "銀", "COMEX先物"),
            ("CL=F", "WTI原油", "NYMEX先物"),
            ("NG=F", "天然ガス", "NYMEX先物"),
            ("BTC-USD", "ビットコイン", "BTC/USD"),
            ("ETH-USD", "イーサリアム", "ETH/USD"),
        ],
    },
    {
        "id": "us_stocks",
        "name": "米国の主要銘柄",
        "note": "時価総額上位を中心としたウォッチリスト",
        "items": [
            ("AAPL", "Apple", "アップル"),
            ("MSFT", "Microsoft", "マイクロソフト"),
            ("NVDA", "NVIDIA", "エヌビディア"),
            ("GOOGL", "Alphabet", "グーグル"),
            ("AMZN", "Amazon", "アマゾン"),
            ("META", "Meta", "メタ"),
            ("TSLA", "Tesla", "テスラ"),
            ("AVGO", "Broadcom", "ブロードコム"),
            ("JPM", "JPMorgan Chase", "JPモルガン"),
            ("BRK-B", "Berkshire Hathaway", "バークシャー"),
            ("LLY", "Eli Lilly", "イーライリリー"),
            ("V", "Visa", "ビザ"),
        ],
    },
    {
        "id": "jp_stocks",
        "name": "日本の主要銘柄",
        "note": "日経平均への影響が大きい銘柄を中心に",
        "items": [
            ("7203.T", "トヨタ自動車", "7203"),
            ("6758.T", "ソニーグループ", "6758"),
            ("9984.T", "ソフトバンクグループ", "9984"),
            ("8306.T", "三菱UFJフィナンシャル・グループ", "8306"),
            ("6861.T", "キーエンス", "6861"),
            ("9983.T", "ファーストリテイリング", "9983"),
            ("6501.T", "日立製作所", "6501"),
            ("8035.T", "東京エレクトロン", "8035"),
            ("6098.T", "リクルートホールディングス", "6098"),
            ("4063.T", "信越化学工業", "4063"),
            ("8058.T", "三菱商事", "8058"),
            ("7011.T", "三菱重工業", "7011"),
        ],
    },
    {
        "id": "etf",
        "name": "主要ETF・ファンド",
        "note": "投資信託の値動きの目安となる上場ファンド",
        "items": [
            ("VOO", "バンガード S&P500 ETF", "米国株式"),
            ("VTI", "バンガード 全米株式 ETF", "米国株式"),
            ("VT", "バンガード 全世界株式 ETF", "全世界株式"),
            ("QQQ", "インベスコ QQQ", "NASDAQ100"),
            ("AGG", "iシェアーズ 米国総合債券 ETF", "米国債券"),
            ("GLD", "SPDR ゴールド・シェア", "金"),
            ("1306.T", "TOPIX連動型上場投信", "日本株式"),
            ("1321.T", "日経225連動型上場投信", "日本株式"),
            ("1557.T", "SPDR S&P500 ETF (東証)", "米国株式"),
            ("2559.T", "MAXIS全世界株式ETF", "全世界株式"),
        ],
    },
]

# (表示名, URL, 言語, focused)
# focused=True は市場専門の配信元。False は総合メディアなので MARKET_KEYWORDS で絞り込む。
NEWS_FEEDS = [
    ("Yahoo!ニュース 経済", "https://news.yahoo.co.jp/rss/topics/business.xml", "ja", False),
    ("NHK 経済", "https://www.nhk.or.jp/rss/news/cat5.xml", "ja", False),
    ("みんかぶ", "https://news.yahoo.co.jp/rss/media/minkabu/all.xml", "ja", False),
    ("Investing.com 日本", "https://jp.investing.com/rss/news_25.rss", "ja", True),
    ("MONEY PLUS", "https://news.yahoo.co.jp/rss/media/moneyplus/all.xml", "ja", False),
    ("東洋経済オンライン", "https://toyokeizai.net/list/feed/rss", "ja", False),
    ("投信・年金", "https://news.yahoo.co.jp/rss/media/toushin/all.xml", "ja", False),
    ("Investing.com", "https://www.investing.com/rss/news_25.rss", "en", True),
    ("CNBC Finance", "https://www.cnbc.com/id/100003114/device/rss/rss.html", "en", True),
    ("MarketWatch", "https://feeds.content.dowjones.io/public/rss/mw_topstories", "en", True),
    ("Yahoo Finance", "https://finance.yahoo.com/news/rssindex", "en", True),
]

# 総合メディアの記事を市場関連に絞り込むためのキーワード（見出しに対して判定する）。
# 「経済」のような広すぎる語は、媒体名や定型句に当たってしまうため入れていない。
MARKET_KEYWORDS = [
    "株価", "株式", "個別株", "相場", "市場", "日経平均", "TOPIX", "ダウ", "ナスダック",
    "S&P", "為替", "円安", "円高", "ドル", "ユーロ", "金利", "利下げ", "利上げ", "日銀",
    "FRB", "FOMC", "債券", "国債", "決算", "上場", "IPO", "投資家", "ファンド",
    "投信", "投資信託", "ETF", "NISA", "iDeCo", "配当", "原油", "商品市況", "金相場",
    "暗号資産", "ビットコイン", "インフレ", "物価", "GDP", "景気", "貿易", "関税",
    "買収", "経済指標", "値上げ", "業績",
]
